export const subscription = {
  id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
  created_at: "2019-08-24T14:15:22Z",
  modified_at: "2019-08-24T14:15:22Z",
  subscription_plan: {
    id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
    created_at: "2019-08-24T14:15:22Z",
    modified_at: "2019-08-24T14:15:22Z",
    type: "Elite",
    description: "string",
    inclusions: [null],
    price: "12",
    duration_in_days: 0,
    number_of_clients: 0,
  },
  client: {
    id: "497f6eca-6276-4993-bfeb-53cbbbba6f08",
    created_at: "2019-08-24T14:15:22Z",
    modified_at: "2019-08-24T14:15:22Z",
    created_by: {
      property1: null,
      property2: null,
    },
    modified_by: {
      property1: null,
      property2: null,
    },
    first_name: "string",
    middle_name: "string",
    user_type: "string",
    phone_number: "string",
    line_address: "string",
    city: "string",
    state: "string",
    country: "string",
    zip_code: "string",
    sex: "string",
    date_of_birth: "2019-08-24",
    height_in_cm: 0,
    weight_in_gm: 0,
    age: 0,
    is_profile_updated: true,
    activity_level: "string",
    somatotype: "string",
    dietary_habits: "string",
    fitness_notes: "string",
    medical_conditions: "string",
    allergies: "string",
    bmi: 0,
    bmi_category: "string",
    bmr: 0,
    tdee: 0,
  },
  start_date: "2019-08-24",
  end_date: "2019-08-24",
  is_active: true,
  is_paused: true,
};

export const subscriptionsList = Array(100)
  .fill(subscription)
  .map((item, index) => {
    return {
      ...item,
      id: index,
      created_at: new Date().toISOString(),
      modified_at: new Date().toISOString(),
      subscription_plan: {
        ...item.subscription_plan,
        id: index,
        created_at: new Date().toISOString(),
        modified_at: new Date().toISOString(),
      },
      client: {
        ...item.client,
        id: index,
        created_at: new Date().toISOString(),
        modified_at: new Date().toISOString(),
        first_name: `Client`,
        last_name: `${index}`,
        phone_number: `+91 999999999${index}`,
      },
      start_date: new Date().toISOString(),
      end_date: new Date().toISOString(),
    };
  });
